version: "2"
services:

  log-generator:
    image: python:3.6-alpine3.7
    restart: "on-failure"
    depends_on:
      - go-fluentd
    networks:
      - fluentd-test
    logging:
      driver: "fluentd"
      options:
        tag: test.sit
        fluentd-address: "127.0.0.1:24225"
        fluentd-async-connect: "true"
        mode: non-blocking
        max-buffer-size: 50m
    volumes:
      - ./app/app.py:/app.py:ro
    command: python /app.py

  go-fluentd:
    image: ppcelery/go-fluentd:1.9.3
    restart: "on-failure"
    networks:
      - fluentd-test
    links:
      - fluentd:fluentd
    depends_on:
      - fluentd
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:24225:24225
    volumes:
      - ./go-fluentd/settings.yml:/etc/go-fluentd/settings.yml:ro
    command: ./go-fluentd --config=/etc/go-fluentd --env=sit  --addr=0.0.0.0:8080 --log-level=info


networks:
  fluentd-test:
    driver: bridge
