version: "3"
services:

  log-generator:
    image: python:3.6-alpine3.7
    restart: "on-failure"
    depends_on:
      - go-fluentd
    logging:
      driver: "fluentd"
      options:
        tag: test.sit
        fluentd-address: "127.0.0.1:24225"
        fluentd-async-connect: "true"
        mode: non-blocking
        max-buffer-size: 1m
    volumes:
      - ./app/app.py:/app.py:ro
    command: python /app.py

  go-fluentd:
    # image: ppcelery/go-fluentd:1.13
    image: ppcelery/go-fluentd:test
    restart: "on-failure"
    ports:
      - 8080:8080
      - 24225:24225
    volumes:
      - ./go-fluentd/settings.yml:/etc/go-fluentd/settings.yml:ro
    command: --config=/etc/go-fluentd/settings.yml
      --env=sit
      --addr=0.0.0.0:8080
      --log-level=info
